username: cube2
password: coffee

application_name: "Imagine Education Uni-Colorado"

gmkey: ABQIAAAASWEk1UdvToR0DcvOwCMx7xTlohoRC1KUZQN04oJlg35Jxm-N9RQPkzSSJfKHSxWKr90pRsTdoRDKSA

gmail_username: 'cube2media@gmail.com'
gmail_password: 'coffee*8